name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

permissions: read-all

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run cargo check
        run: cargo check --verbose --tests
      - name: Run cargo clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Run cargo fmt
        run: cargo fmt --verbose --check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Run cargo test
        run: cargo test --verbose
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MSRV
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.37.0"
      - name: Check MSRV compatibility
        run: cargo check --verbose --tests
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Run cargo doc
        run: cargo doc --verbose
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "target/doc/"
  deploy-docs:
    needs: build-docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write    # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
